# Generated by Django 5.1.3 on 2025-12-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising_app', '0002_course_day_course_end_time_course_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'section')},
        ),
    ]
