# Generated by Django 5.1.3 on 2025-12-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising_app', '0003_course_room_course_section_alter_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisees', to='advising_app.faculty'),
        ),
    ]
